# Eliminating 'no visible binding' note
utils::globalVariables(c(
  "person",
  "dl_datetime",
  "to_datetime",
  ".data",
  "start_datetime",
  "end_datetime",
  "account_handle",
  "contentDetails.videoPublishedAt",
  "account",
  "account_id",
  "account_url",
  "published_time",
  "items",
  "doubts_var",
  "handle",
  "list_id",
  "id"
))
